version: 2.0
title: All Loops Considered
tagline:
description: Programming et al.
url: https://all-loops-considered.org
baseurl: ""
highlighter: rouge
permalink: pretty
url: https://github.com/mpicard

author:
  name: 'Martin Picard'
paginate: 5
  email: martin8768@gmail.com

github:
  repo: https://github.com/mpicard/mpicard.github.io

plugins:
  - jekyll-paginate
  - jekyll-gist

port: 4444
