port: 4444
markdown: redcarpet
highlighter: rouge

permalink: pretty

title: All Loops Considered
tagline:
description: Programming, et al.
url: http://all-loops-considered.org
baseurl: ""

author:
  name: 'Martin Picard'
  url: https://github.com/mpicard
  email: martin8768@gmail.com

paginate: 5

version: 2.0.0

github:
  repo: https://github.com/mpicard/mpicard.github.io

gems:
  - jekyll-paginate
  - jekyll-gist
